config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :beasts
  resources :tags

end

app/models/beast.rb
class Beast < ActiveRecord::Base

  has_and_belongs_to_many :tags

end

app/models/beasts_tags.rb
class BeastsTags < ActiveRecord::Base
  belongs_to :beast
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :beasts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beasts_controller.rb
class BeastsController < ApplicationController

  def index
    @beasts = Beast.all
    @tags = Tag.all
  end

  def new
    @beast = Beast.new
    @tags = Tag.all
  end

  def create
    @beast = Beast.create(beast_params)
    tags = params[:beast][:tag_ids]
    tags.each do |tag_id|
      @beast.tags << Tag.find(tag_id) unless tag_id.blank?
    end
    redirect_to @beast
  end

  def show
    @beast = Beast.find(params[:id])
    @tags = @beast.tags
    list = flickr.photos.search :text => @beast.name, :sort => "relevance"
    number = rand(0..3)
    id = list[number].id
    secret = list[number].secret
    info = flickr.photos.getInfo :photo_id => id, :secret => secret
    @url = FlickRaw.url(info)

  end

  def edit
    @beast = Beast.find(params[:id])
    @tags = Tag.all
  end

  def update
    @beast = Beast.update(params[:id], beast_params)

    @beast.tags.clear
    tags = params[:beast][:tag_ids]
    tags.each do |tag_id|
      @beast.tags << Tag.find(tag_id) unless tag_id.blank?
    end
    redirect_to @beast
  end

  def destroy
    @beast = Beast.find(params[:id])
    @beast.destroy
    redirect_to beasts_path
  end

  private

  def beast_params
    params.require(:beast).permit(:name,:description)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(tag_params)
    @tags = Tag.all
    redirect_to tags_path
  end

  def show
    @tag = Tag.find(params[:id])
    @beasts = @tag.beasts
  end

  def destroy
    @tag = Tag.find(params[:id])
    if @tag.beasts.length < 1
      @tag.destroy
    else
      flash[:danger] = "Can't delete; tag is currently assigned to a beast."
    end
    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beasts/edit.html.erb
<center>
<h1>Edit <%= @beast.name %></h1>
  <div class="input-group">

    <%= bootstrap_form_for(@beast) do |f| %>
    <%= f.text_field :name, hide_label: true, placeholder: "Enter a beast" %>
    <%= f.text_field :description, hide_label: true, placeholder: "Description" %>

    <%= f.collection_check_boxes :tag_ids, @tags, :id, :name, hide_label: true %>

    <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>

  </div>
</center>

app/views/beasts/index.html.erb
<center>
<h1>Beasts</h1>
<h2>I'M THE CAPTAIN NOW</h2>

<div class="beast-list">
<% @beasts.each do |b| %>
<li><%= link_to b.name, b %></li>
<% end %>
</div>
</center>

app/views/beasts/new.html.erb
<center>
  <h1>Add a beast</h1>
  <div class="input-group">

    <%= bootstrap_form_for(@beast) do |f| %>
    <%= f.text_field :name, hide_label: true, placeholder: "Enter a beast" %>
    <%= f.text_field :description, hide_label: true, placeholder: "Description" %>

    <%= f.collection_check_boxes :tag_ids, @tags, :id, :name, hide_label: true %>

    <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>

  </div>
</center>

app/views/beasts/show.html.erb
<center>
  <div class="show-left">
    <img src="<%= @url %>">
  </div>
  <div class="show-right">
    <h1><%= @beast.name %></h1>
    <p>
      <strong>Description:</strong>
      <%= @beast.description %>
    </p>

    <p>
      <strong>Tags:</strong>
      <% @beast.tags.each do |f| %>
      <span class="label label-primary"><%= f.name %></span>
      <% end %>
    </p>

    <%= link_to 'Edit', edit_beast_path(@beast) %> |
    <%= link_to 'Back', beasts_path %> |
    <%= link_to 'Delete', beast_path,
    method: :delete,
    data: { confirm: 'Are you sure?' } %>
  </div>
</center>

app/views/layouts/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
  <%= v %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fantastic Beasts and Where to Find Them</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link href='//fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js'></script>
</head>
<body>

  <nav class="navbar navbar-default text-center">
    <div class="container text-center">
    <img src="http://fontmeme.com/embed.php?text=Fantastic%20Beasts&name=Lumos.ttf&size=110&style_color=ffffff">
      <h1 id="header">And Where To Find Them</h1>
    </div>
    <div class="container">

      <div class="btn-group" role="group" aria-label="...">
        <div class="btn-group" role="group">
          <a class='btn btn-default' href='/'>Home</a>
        </div>
        <div class="btn-group" role="group">
          <a class="btn btn-default" href='/beasts'>View all beasts</a>
        </div>
        <div class="btn-group" role="group">
          <a class="btn btn-default" href='/beasts/new'>Add new beast</a>
        </div>
        <div class="btn-group" role="group">
          <a class="btn btn-default" href='/tags'>View all tags</a>
        </div>
        <div class="btn-group" role="group">
          <a class="btn btn-default" href='/tags/new'>Add new tag</a>
        </div>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/tags/index.html.erb
<center>
<h1>Tags</h1>

<%= render "layouts/flash" %>

<div class="beast-list">
<% @tags.each do |t| %>
<li><%= link_to t.name, t %>

  <%= link_to 'Delete', t, class: "btn btn-danger",
  method: :delete,
  data: { confirm: 'Are you sure?' } %>

</li>

<% end %>
</div>
</center>

app/views/tags/new.html.erb
<center>
  <h1>Add a tag</h1>
  <div class="input-group">

    <%= bootstrap_form_for @tag do |f| %>
    <%= f.text_field :name, hide_label: true, placeholder: "Enter a tag" %>
    <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>

  </div>
</center>

app/views/tags/show.html.erb
<center><h1><%= @tag.name %></h1>

  <div class="beast-list">
    <% @tag.beasts.each do |f| %>
    <li><a href="/beasts/<%= f[:id] %>"><%= f.name %></a></li>
    <% end %>

  </div>
</center>

app/views/welcome/index.html.erb
<div id="carousel-example-generic" class="carousel slide text-center" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="https://ivannatalkalot.files.wordpress.com/2013/07/buckbeak.jpg">
    </div>
    <div class="item">
      <img src="http://images4.fanpop.com/image/polls/780000/780077_1311246409575_full.jpg">
    </div>
    <div class="item">
      <img src="http://i59.tinypic.com/314b13s.jpg">
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>